### ISSUE TITLE
Difference between LightSync, ChromaControl and CueSDK

### ISSUE THREAD

**Issue by OAlienado** [AndrewBabbitt97/LightSync#1]
Hello @AndrewBabbitt97 , how are you doing? Once again, thanks for the amazing work!

This is not really an issue, and more like a question... in your profile there is a LightSync and a CueSDK, but in Reddit you spoke about a ChromaControl - that has a profile of its own. So, I wonder: what's the difference between them, and which one I must use to control my Corsair devices through Razer Synapse, alongside my Asus stuff? 

Thank you, once again!

**Comment by Orvyasis** [comment]
I also want to know this.

**Comment by AndrewBabbitt97** [comment]
There's technically one other project related to all of this known as RGB Kit.

CUE SDK is a .NET wrapper around Corsairs iCUR SDK, it is only for software developers to consume and allows a developer to programmatically control iCUE devices.

AuraConnect was where everything started, it's super basic in structure and was designed to do one thing and do it well: Take Synapse RGB commands and forward it to AURA allowing control of AURA devices. This uses ASUS's AURA SDK which comes when you install AURA or Armory Crate. It's a COM component and so can be called directly from .NET.

RGB Kit is a RGB lighting SDK allowing for control over ASUS and Corsair devices, it abstracts things and gives a simple interface to control any RGB Device regardless of who made it. 

ChromaControl started off the idea of AuraConnect but to use more abstractions and provide support for multiple devices manufacturers, this is when RGB Kit was created to serve the abstractions.

Then that leaves you wondering about LightSync, to be honest I just entirely forgot to archive this project lol. This project turned into RGB Kit and ChromaControl. It's essentially what both of those projects are just merged into one, I wanted to split them to make the device control components (RGB Kit) more easily consumable.

**Comment by Orvyasis** [comment]
Okay, just checked out Chroma Control. Not working as of now for me (iCue and Aura aren't popping up on Razer Synapse anywhere unless I use AuraConnect). But I'm super keen to see this in action! You should start a Patreon or GoFundMe or something!

**Comment by AndrewBabbitt97** [comment]
I actually have a github sponsor page that acts similar to a patreon here: https://github.com/sponsors/AndrewBabbitt97

I have been reworking stuff in my free time on ChromaControl, eventually AuraConnect will be archived as well.

One of the big things I'm looking at right now requires code signing, which I really want to do but code signing certs aren't that cheep (especially conspidering certs have to be renewed as well). So support on sponsors helps a lot for stuff like that. This can help with stuff like Antivirus trust and allowing me to install windows 10 app packages (MSIX) rather than the old style installer (auto updates are coming by the way).
